import { useEffect, useState } from "react";
import type { MenyuApi } from "../api";
import { checkInAttention } from "../attention";
import { useI18n } from "../i18n";
import type { BackupSummary, EventConfiguration, EventData, EventLifecycleState, EventReport, Staff, Workspace } from "../types";
import { eventLocalInputToIso, formatEventDateTime, isoToEventLocalInput, yen } from "../utils";
import EventConfigurationFields, { legacyConfiguration } from "./EventConfigurationFields";
import { Button, Icon } from "./ui";

type CreatePayload = { name: string; eventTime: string; prelimsStartTime: string; location: string; timeZone: string; mode: EventData["mode"]; judges: string[]; configuration: EventConfiguration; state: EventLifecycleState };
type Props = {
  api: MenyuApi; event: EventData | null; eventId: string; report: EventReport | null; staff: Staff; events: EventData[];
  onSelectEvent: (eventId: string) => void; onRenameEvent: (eventId: string, name: string) => Promise<void>;
  onSetArchiveState: (eventId: string, action: "archive" | "restore") => Promise<void>; onDeleteEvent: (eventId: string) => Promise<void>;
  onWorkspace: (workspace: Workspace) => void; onCreateEvent: (payload: CreatePayload) => Promise<void>; onMarkPresent: () => Promise<void>;
  refresh: () => Promise<void>; notify: (message: string, error?: boolean) => void; writeDisabled?: boolean;
};

function EventSetup({ onCreateEvent, writeDisabled = false }: Pick<Props, "onCreateEvent" | "writeDisabled">) {
  const { t } = useI18n();
  const [name, setName] = useState("CHIP CHOP"); const [eventTime, setEventTime] = useState(""); const [prelimsStartTime, setPrelimsStartTime] = useState("");
  const [location, setLocation] = useState("Tokyo, Japan"); const [mode, setMode] = useState<EventData["mode"]>("live"); const [configuration, setConfiguration] = useState<EventConfiguration>(legacyConfiguration); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!name.trim()) return; setBusy(true); try { await onCreateEvent({ name: name.trim(), eventTime: eventLocalInputToIso(eventTime), prelimsStartTime: eventLocalInputToIso(prelimsStartTime), location: location.trim() || "Tokyo, Japan", timeZone: "Asia/Tokyo", mode, judges: [], configuration, state: "draft" }); } finally { setBusy(false); } };
  return <section className="setup-card"><div className="setup-intro"><h1>{t("overview.startDesk")}</h1><p>{t("overview.createHelp")}</p><ol className="setup-checklist"><li>{t("overview.setup1")}</li><li>{t("overview.setup2")}</li><li>{t("overview.setup3")}</li></ol></div><div className="setup-fields"><label className="field"><span>{t("overview.eventName")}</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>{t("overview.location")}</span><input value={location} onChange={(event) => setLocation(event.target.value)} /></label><label className="field"><span>{t("overview.time")} <i>{t("common.optional")}</i></span><input type="datetime-local" value={eventTime} onChange={(event) => setEventTime(event.target.value)} /></label><label className="field"><span>{t("overview.prelimsTime")} <i>{t("common.optional")}</i></span><input type="datetime-local" value={prelimsStartTime} onChange={(event) => setPrelimsStartTime(event.target.value)} /></label><label className="setup-mode"><input type="checkbox" checked={mode === "rehearsal"} onChange={(event) => setMode(event.target.checked ? "rehearsal" : "live")} /><span><strong>{mode === "rehearsal" ? t("overview.rehearsal") : t("overview.live")}</strong><small>{t("overview.rehearsalHelp")}</small></span></label><EventConfigurationFields value={configuration} onChange={setConfiguration} /></div><Button variant="primary" busy={busy} busyLabel={t("overview.creating")} disabled={writeDisabled || !name.trim() || configuration.divisions.some((division) => !division.name || !division.id)} aria-describedby={writeDisabled ? "offline-write-help" : undefined} onClick={submit}>{t("overview.create")}</Button></section>;
}

function EventManager({ events, eventId, onSelectEvent, onRenameEvent, onSetArchiveState, onDeleteEvent, notify, writeDisabled = false }: Pick<Props, "events" | "eventId" | "onSelectEvent" | "onRenameEvent" | "onSetArchiveState" | "onDeleteEvent" | "notify" | "writeDisabled">) {
  const { language, t } = useI18n(); const [busy, setBusy] = useState("");
  const run = async (key: string, action: () => Promise<void>) => { if (writeDisabled) return notify(t("state.offlineWrite"), true); try { setBusy(key); await action(); } finally { setBusy(""); } };
  const rename = (item: EventData) => { const name = window.prompt(t("overview.eventName"), item.name); if (name && name.trim() && name.trim() !== item.name) run(`rename-${item.id}`, () => onRenameEvent(item.id, name.trim())); };
  const archive = (item: EventData) => { if (window.confirm(t("event.archiveConfirm", { name: item.name }))) run(`archive-${item.id}`, () => onSetArchiveState(item.id, "archive")); };
  const remove = (item: EventData) => { if (window.prompt(t("event.deletePrompt", { name: item.name })) !== "DELETE") return notify(t("toast.deleteCanceled")); run(`delete-${item.id}`, () => onDeleteEvent(item.id)); };
  return <article className="operations-card event-manager"><div><h2>{t("overview.manage")}</h2><p>{t("overview.manageHelp")}</p></div><div className="event-manager-list">{events.map((item) => { const archived = item.lifecycle?.status === "archived"; return <div className={`${archived ? "event-manager-row archived" : "event-manager-row"}${item.id === eventId ? " current" : ""}`} key={item.id}><div><strong>{item.name} {item.mode === "rehearsal" && <small className="event-mode-label">· {t("overview.rehearsal")}</small>}</strong><small>{formatEventDateTime(item.eventTime || item.createdAt, item.timeZone, language)} · {t("overview.registrations", { count: item.registrations.length })}</small></div><div className="event-manager-actions">{!archived ? <><Button size="sm" disabled={Boolean(busy)} onClick={() => onSelectEvent(item.id)}>{t("common.open")}</Button><Button size="sm" disabled={Boolean(busy)} onClick={() => rename(item)}>{t("common.rename")}</Button><Button variant="secondary" size="sm" disabled={Boolean(busy)} onClick={() => archive(item)}>{t("common.archive")}</Button></> : <><Button variant="primary" size="sm" busy={busy === `restore-${item.id}`} disabled={Boolean(busy)} onClick={() => run(`restore-${item.id}`, () => onSetArchiveState(item.id, "restore"))}>{t("common.restore")}</Button><Button variant="danger" size="sm" disabled={Boolean(busy)} onClick={() => remove(item)}>{t("common.delete")}</Button></>}</div></div>; })}{!events.length && <p className="muted">{t("overview.noEvents")}</p>}</div></article>;
}

function BackupCard({ api, eventId, staff, refresh, notify, event, writeDisabled = false }: Pick<Props, "api" | "eventId" | "staff" | "refresh" | "notify" | "event" | "writeDisabled">) {
  const { language, t } = useI18n(); const [backups, setBackups] = useState<BackupSummary[]>([]); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { setBackups((await api.backups(eventId)).backups); } catch (error) { notify(error instanceof Error ? error.message : String(error), true); } };
  useEffect(() => { load(); }, [eventId]);
  const create = async () => { if (writeDisabled) return notify(t("state.offlineWrite"), true); try { setBusy(true); await api.createBackup(eventId, reason.trim(), staff); setReason(""); await refresh(); await load(); notify(t("toast.backupSaved")); } catch (error) { notify(error instanceof Error ? error.message : String(error), true); } finally { setBusy(false); } };
  const restore = async (backup: BackupSummary) => { if (writeDisabled) return notify(t("state.offlineWrite"), true); if (!window.confirm(t("event.restoreConfirm"))) return; try { setBusy(true); await api.restoreBackup(eventId, backup.backupId, staff); await refresh(); await load(); notify(t("toast.backupRestored")); } catch (error) { notify(error instanceof Error ? error.message : String(error), true); } finally { setBusy(false); } };
  return <article className="operations-card backup-card"><div><h2>{t("overview.backups")}</h2><p>{t("overview.backupHelp")}</p></div><div className="backup-create"><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder={t("overview.reason")} aria-label={t("overview.reason")} /><Button variant="secondary" busy={busy} busyLabel={t("state.saving")} onClick={create}>{t("overview.createBackup")}</Button></div><div className="backup-list">{backups.map((backup) => <div key={backup.backupId}><span><strong>{backup.kind === "pre_restore" ? t("overview.safety") : backup.kind === "import" ? t("overview.importSnapshot") : t("overview.manual")}</strong><small>{formatEventDateTime(backup.createdAt, event?.timeZone, language)} · {t("overview.registrations", { count: backup.registrationCount })}</small></span><Button variant="danger" size="sm" disabled={busy} onClick={() => restore(backup)}>{t("overview.restoreBackup")}</Button></div>)}{!backups.length && <p className="muted">{t("overview.noBackups")}</p>}</div></article>;
}

function EventSettings({ api, event, staff, refresh, notify, writeDisabled = false }: Pick<Props, "api" | "event" | "staff" | "refresh" | "notify" | "writeDisabled"> & { event: EventData }) {
  const { t } = useI18n(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [draft, setDraft] = useState(() => ({ name: event.name, location: event.location, eventTime: isoToEventLocalInput(event.eventTime, event.timeZone), prelimsStartTime: isoToEventLocalInput(event.prelimsStartTime, event.timeZone), mode: event.mode, state: event.lifecycle.status, configuration: event.configuration }));
  useEffect(() => setDraft({ name: event.name, location: event.location, eventTime: isoToEventLocalInput(event.eventTime, event.timeZone), prelimsStartTime: isoToEventLocalInput(event.prelimsStartTime, event.timeZone), mode: event.mode, state: event.lifecycle.status, configuration: event.configuration }), [event]);
  const save = async () => { if (writeDisabled) return notify(t("state.offlineWrite"), true); try { setBusy(true); await api.updateEvent(event.id, { name: draft.name.trim(), location: draft.location.trim(), timeZone: "Asia/Tokyo", eventTime: eventLocalInputToIso(draft.eventTime), prelimsStartTime: eventLocalInputToIso(draft.prelimsStartTime), mode: draft.mode, state: draft.state, configuration: draft.configuration }, staff); await refresh(); setOpen(false); notify(t("toast.eventSettingsSaved")); } catch (error) { notify(error instanceof Error ? error.message : String(error), true); } finally { setBusy(false); } };
  const lockedDivisionIds = event.registrations.length ? event.configuration.divisions.filter((division) => event.registrations.some((registration) => registration.bracket === division.id)).map((division) => division.id) : [];
  return <article className="operations-card event-settings"><div className="report-card-heading"><div><span className="card-label">{t("overview.eventSettings")}</span><h2>{event.name}</h2></div><Button size="sm" onClick={() => setOpen(!open)}>{open ? t("common.close") : t("common.edit")}</Button></div>{open ? <div className="settings-grid"><label className="field"><span>{t("overview.eventName")}</span><input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label className="field"><span>{t("overview.location")}</span><input value={draft.location} onChange={(e) => setDraft({ ...draft, location: e.target.value })} /></label><label className="field"><span>{t("overview.time")}</span><input type="datetime-local" value={draft.eventTime} onChange={(e) => setDraft({ ...draft, eventTime: e.target.value })} /></label><label className="field"><span>{t("overview.prelimsTime")}</span><input type="datetime-local" value={draft.prelimsStartTime} onChange={(e) => setDraft({ ...draft, prelimsStartTime: e.target.value })} /></label><label className="field"><span>Event state</span><select value={draft.state} onChange={(event) => setDraft({ ...draft, state: event.target.value as EventLifecycleState })}><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label><label className="setup-mode"><input type="checkbox" checked={draft.mode === "rehearsal"} onChange={(e) => setDraft({ ...draft, mode: e.target.checked ? "rehearsal" : "live" })} /><span><strong>{draft.mode === "rehearsal" ? t("overview.rehearsal") : t("overview.live")}</strong><small>{t("overview.rehearsalHelp")}</small></span></label><EventConfigurationFields value={draft.configuration} onChange={(configuration) => setDraft({ ...draft, configuration })} lockedDivisionIds={lockedDivisionIds} /><p className="settings-safety-note">Division IDs and team sizes are protected once people are registered. Prelim, bracket, and fee changes are protected once event-day records depend on them.</p><Button variant="primary" busy={busy} busyLabel={t("state.saving")} disabled={writeDisabled || !draft.name.trim() || draft.configuration.divisions.some((division) => !division.name || !division.id)} onClick={save}>{t("common.save")}</Button></div> : <p>{event.location || "Tokyo, Japan"} · Asia/Tokyo · {event.lifecycle.status} · {event.mode === "rehearsal" ? t("overview.rehearsal") : t("overview.live")}</p>}</article>;
}

export default function OverviewWorkspace(props: Props) {
  const { language, t } = useI18n(); const { api, event, eventId, report, staff, events, onSelectEvent, onRenameEvent, onSetArchiveState, onDeleteEvent, onWorkspace, onCreateEvent, onMarkPresent, refresh, notify, writeDisabled = false } = props;
  if (!event) return <><EventSetup onCreateEvent={onCreateEvent} writeDisabled={writeDisabled} /><section className="operations-grid single"><EventManager events={events} eventId={eventId} onSelectEvent={onSelectEvent} onRenameEvent={onRenameEvent} onSetArchiveState={onSetArchiveState} onDeleteEvent={onDeleteEvent} notify={notify} writeDisabled={writeDisabled} /></section>{writeDisabled && <p id="offline-write-help" className="sr-only">{t("state.offlineWrite")}</p>}</>;
  const totals = report?.totals; const attendees = report?.staffAttendance || event.staffAttendance || [];
  const attentionCount = checkInAttention(event.registrations, report?.auditLog || []).reduce((sum, item) => sum + item.count, 0);
  const teamTotal = totals?.totalTeams ?? 0;
  const checkedInTeams = totals?.checkedInTeams ?? 0;
  const totalBattlers = totals?.totalBattlers ?? 0;
  const checkedInBattlers = totals?.checkedInBattlers ?? 0;
  return <>
    <header className="workspace-heading compact-heading"><div><h1 className={/^\d+v\d+$/i.test(event.name) ? "division-title" : undefined}>{event.name}</h1><p>{event.location || "Tokyo, Japan"} · {formatEventDateTime(event.eventTime, event.timeZone, language) || t("common.notSet")}</p></div><span className="status-pill good">● {event.mode === "rehearsal" ? t("overview.rehearsal") : t("shell.live")}</span></header>
    <section className="staff-home" aria-label={t("overview.eventSummary")}>
      <dl className="staff-home__summary" aria-label={t("overview.eventSummary")}>
        <div><dt>{t("overview.teams")}</dt><dd>{checkedInTeams}<span> / {teamTotal}</span></dd><small>{t("overview.checkinSummary", { checkedIn: checkedInTeams, total: teamTotal })}</small></div>
        <div><dt>{t("overview.battlers")}</dt><dd>{checkedInBattlers}<span> / {totalBattlers}</span></dd><small>{t("overview.prelimsSummary", { count: checkedInBattlers })}</small></div>
        <div><dt>{t("overview.spectators")}</dt><dd>{totals?.spectators ?? event.spectators.count}</dd><small>{totals?.canceled ?? 0} {t("status.Canceled").toLowerCase()}</small></div>
        <div className="staff-home__cash"><dt>{t("overview.cash")}</dt><dd>{totals ? yen(totals.totalCash) : t("common.notSet")}</dd><small>{t("reports.drinks")}: {totals ? yen(totals.drinkMoney) : t("common.notSet")}</small></div>
      </dl>
      <section className="staff-home__routes" aria-label={t("overview.workspaces")}>
        <div>
          <button type="button" onClick={() => onWorkspace("checkin")}><span className="staff-home__route-number">01</span><span className="staff-home__route-copy"><strong>{t("nav.checkin")}</strong><small>{t("overview.checkinSummary", { checkedIn: checkedInTeams, total: teamTotal })}</small></span><span className="staff-home__route-action">{t("overview.launchCheckin")} <Icon name="arrowRight" size={14} /></span></button>
          <button type="button" onClick={() => onWorkspace("prelims")}><span className="staff-home__route-number">02</span><span className="staff-home__route-copy"><strong>{t("nav.prelims")}</strong><small>{t("overview.prelimsSummary", { count: checkedInBattlers })}</small></span><span className="staff-home__route-action">{t("overview.launchPrelims")} <Icon name="arrowRight" size={14} /></span></button>
          <button type="button" onClick={() => onWorkspace("bracket")}><span className="staff-home__route-number">03</span><span className="staff-home__route-copy"><strong>{t("nav.bracket")}</strong><small>{t("overview.bracketSummary")}</small></span><span className="staff-home__route-action">{t("overview.launchBracket")} <Icon name="arrowRight" size={14} /></span></button>
        </div>
      </section>
      {attentionCount > 0 && <section className="staff-home__attention" aria-label={t("shell.attention")}><div><strong>{t("shell.attention")}</strong><span>{t("overview.attentionHelp", { count: attentionCount })}</span></div><button type="button" onClick={() => onWorkspace("checkin")}>{t("overview.reviewCheckin")} <Icon name="arrowRight" size={14} /></button></section>}
    </section>
    <section className="operations-grid"><EventSettings api={api} event={event} staff={staff} refresh={refresh} notify={notify} writeDisabled={writeDisabled} /><article className="operations-card"><div><h2>{t("overview.staff")}</h2></div><Button variant="secondary" disabled={writeDisabled} aria-describedby={writeDisabled ? "offline-write-help" : undefined} onClick={onMarkPresent}>{t("overview.markPresent")}</Button><ul className="staff-list">{attendees.map((person) => <li key={person.key}><strong>{person.name}</strong><span>{person.role}</span><small>{formatEventDateTime(person.lastActiveAt, event.timeZone, language)}</small></li>)}{!attendees.length && <li className="muted">{t("overview.noStaff")}</li>}</ul></article><BackupCard api={api} event={event} eventId={eventId} staff={staff} refresh={refresh} notify={notify} writeDisabled={writeDisabled} /><EventManager events={events} eventId={eventId} onSelectEvent={onSelectEvent} onRenameEvent={onRenameEvent} onSetArchiveState={onSetArchiveState} onDeleteEvent={onDeleteEvent} notify={notify} writeDisabled={writeDisabled} /></section>{writeDisabled && <p id="offline-write-help" className="sr-only">{t("state.offlineWrite")}</p>}
  </>;
}
