import { createContext, useContext, useMemo, useState } from "react";

export type Language = "en" | "ja";
type Params = Record<string, string | number>;

export const en: Record<string, string> = {
  "app.staffOnly": "Staff only", "app.openDesk": "Open the event desk", "app.authHelp": "Enter the shared access code, then identify yourself for the activity log.", "app.staffName": "Staff name", "app.roles": "Role or roles", "app.accessCode": "Staff access code", "app.enter": "Enter staff desk", "app.checking": "Checking access…", "app.connecting": "Connecting to The Menyu…", "app.connectingHelp": "Checking staff access and the event connection.", "app.connectionFailed": "The Menyu is not reachable.", "app.retry": "Retry", "app.sessionExpired": "Your staff session expired. Sign in again.", "app.chooseEventFirst": "Choose an event before opening this workspace.",
  "state.requestFailed": "That action could not be completed.", "state.refreshed": "The event changed elsewhere. The latest state is loaded.", "state.offlineTitle": "Offline — changes are paused", "state.offlineHelp": "You can keep reading and searching. Live changes cannot be recorded until reconnection.", "state.retryNow": "Retry now", "state.offlineWrite": "Reconnect before recording a live change.", "state.reconnected": "Reconnected. Live changes can be recorded again.",
  "nav.now": "Now", "nav.checkin": "Check-in", "nav.prelims": "Prelims", "nav.bracket": "Bracket", "nav.display": "Display", "nav.records": "Records", "nav.settings": "Settings",
  "shell.control": "Event control", "shell.event": "Active event", "shell.chooseEvent": "Choose an event", "shell.currentPhase": "Current phase", "shell.currentWorkspace": "Current phase", "shell.openStatus": "OPEN", "shell.workspaceNavigation": "Workspace navigation", "shell.openNavigation": "Open navigation", "shell.status": "Event status", "shell.nextMilestone": "Up next", "shell.present": "Present", "shell.attention": "Attention", "shell.lastSync": "Last sync", "shell.syncedNow": "Synced now", "shell.syncing": "Syncing…", "shell.offline": "Offline · retrying", "shell.notSynced": "Not synced", "shell.prelimsUnset": "Prelims time not set", "shell.prelimsStarted": "Prelims started", "shell.prelimsIn": "Prelims in {time}", "shell.signedIn": "Signed in as", "shell.signOut": "Sign out", "shell.rolesHelp": "Roles highlight your usual workspace. Every workspace remains editable.", "shell.customRole": "Custom role", "shell.connection": "Connection settings", "shell.apiUrl": "Backend API URL", "shell.live": "LIVE",
  "shell.workspaceAttention": "Attention",
  "division.2v2": "2v2 Battle", "division.under15": "Under-15 1v1", "status.Registered": "Waiting", "status.Partial": "Partial", "status.Checked in": "Present", "status.Canceled": "Canceled", "status.paid": "Paid", "status.paymentPending": "Payment pending",
  "common.open": "Open", "common.close": "Close", "common.edit": "Edit", "common.save": "Save changes", "common.cancel": "Cancel", "common.restore": "Restore", "common.delete": "Delete", "common.rename": "Rename", "common.archive": "Archive", "common.reload": "Reload", "common.optional": "optional", "common.all": "All", "common.none": "None", "common.yes": "Yes", "common.no": "No", "common.shown": "{count} shown", "common.notSet": "Not set", "common.export": "Export", "common.back": "Back",
  "attention.title": "Review queue", "attention.partial": "Incomplete teams", "attention.partialHelp": "One or more team members still need check-in", "attention.duplicates": "Duplicate warnings", "attention.duplicatesHelp": "Review, ignore, or remove possible duplicates", "attention.review": "Records needing review", "attention.reviewHelp": "Imported information is incomplete or unclear", "attention.payment": "Same-day payments pending", "attention.paymentHelp": "Created at the door but check-in is not complete", "attention.late": "Late arrivals", "attention.lateHelp": "Added after the prelim order was locked", "attention.unscored": "Prelim scores missing", "attention.unscoredHelp": "Checked-in entries still need two scores", "attention.noOrder": "Prelim order not locked", "attention.noBracket": "Bracket not generated", "attention.openMatches": "Open matches", "attention.openMatchesHelp": "Finish the active matches before closing the bracket", "attention.clear": "Nothing to review in this workspace.",
  "activity.title": "Recent activity", "activity.viewAll": "View all", "activity.empty": "No activity recorded yet.", "activity.system": "System", "activity.check_in": "checked in", "activity.undo_check_in": "check-in undone", "activity.create_same_day_registration": "same-day registration created", "activity.import_csv": "CSV imported", "activity.edit_registration": "registration updated", "activity.add_spectator": "spectator payment recorded", "activity.enter_score": "prelim score entered", "activity.generate_prelim_order": "prelim order locked", "activity.create_bracket": "bracket generated", "activity.record_bracket_decision": "match result recorded", "activity.control_shared_timer": "timer updated", "activity.append_late_arrival": "late arrival appended", "activity.cancel_registration": "registration canceled", "activity.restore_registration": "registration restored", "activity.ignore_duplicate_warning": "duplicate warning ignored", "activity.remove_duplicate_registration": "duplicate removed", "activity.create_event": "event created", "activity.update_event": "event updated", "activity.archive_event": "event archived", "activity.restore_event": "event restored",
  "overview.title": "Now", "overview.pulse": "Event status", "overview.location": "Location", "overview.time": "Event time", "overview.teams": "2v2 teams", "overview.battlers": "Battlers present", "overview.spectators": "Spectators", "overview.cash": "Cash collected", "overview.launchCheckin": "Open check-in", "overview.launchPrelims": "Open prelims", "overview.launchBracket": "Open bracket", "overview.staffHome": "Event desk", "overview.startHere": "Start your shift", "overview.startHereHelp": "Use the active workspace for the next job on the floor.", "overview.eventSummary": "Event summary", "overview.checkinSummary": "{checkedIn} of {total} teams checked in", "overview.prelimsSummary": "{count} battlers checked in", "overview.bracketSummary": "Set the bracket and record match results", "overview.workspaces": "Event workspaces", "overview.workspacesHelp": "Choose the workspace that matches the work in front of you.", "overview.attentionHelp": "{count} check-in items need a review.", "overview.reviewCheckin": "Review check-in", "overview.newEvent": "New event", "overview.startDesk": "Start an event desk", "overview.createHelp": "Create a clean event record. Tokyo and Japan Standard Time are the defaults.", "overview.eventName": "Event name", "overview.prelimsTime": "Prelims start time", "overview.judge1": "Judge 1", "overview.judge2": "Judge 2", "overview.create": "Create event", "overview.creating": "Creating…", "overview.manage": "Manage event records", "overview.manageHelp": "Archive finished events to remove them from the picker. Permanent deletion also removes backups.", "overview.noEvents": "No event records yet.", "overview.registrations": "{count} registrations", "overview.staff": "Staff on floor", "overview.markPresent": "Mark me present", "overview.noStaff": "No staff attendance recorded yet.", "overview.backups": "Event backups", "overview.backupHelp": "Create a recovery point before a major event operation.", "overview.reason": "Reason (optional)", "overview.createBackup": "Create backup", "overview.noBackups": "No recovery points yet.", "overview.restoreBackup": "Restore backup",
  "checkin.title": "Check-in live", "checkin.flowHelp": "Search an entry, confirm the members, then record each arrival.", "checkin.controls": "Arrival controls", "checkin.search": "Search name, team, ID, email, or Instagram", "checkin.add": "Add registration", "checkin.import": "Import CSV", "checkin.spectator": "Add spectator · ¥2,700", "checkin.waiting": "Waiting", "checkin.partial": "Partial", "checkin.present": "Present", "checkin.review": "Needs review", "checkin.registration": "Registration", "checkin.division": "Division", "checkin.status": "Status", "checkin.payment": "Payment", "checkin.noMatches": "No matching registrations.", "checkin.select": "Select a registration", "checkin.selectHelp": "Choose a team or battler from the list to manage check-in.", "checkin.teamMembers": "Team members", "checkin.member": "Member", "checkin.checkIn": "Check in", "checkin.undo": "Undo check-in", "checkin.checkedAt": "Checked in {time}", "checkin.collect": "Collect {amount}", "checkin.recordArrivalPayment": "Record arrival & payment", "checkin.entry": "Entry", "checkin.drink": "Drink", "checkin.notes": "Notes", "checkin.noNotes": "No notes added.", "checkin.early": "Early signup", "checkin.sameDay": "Same-day", "checkin.needsReview": "Needs review", "checkin.duplicate": "Possible duplicate", "checkin.ignoreDuplicate": "Ignore warning", "checkin.removeDuplicate": "Remove duplicate", "checkin.addWalkIn": "Add a walk-in", "checkin.teamName": "Team name", "checkin.battlerName": "Battler name", "checkin.memberNames": "Member names", "checkin.email": "Contact email", "checkin.instagram": "Instagram", "checkin.dob": "Date of birth", "checkin.parent": "Parent / guardian", "checkin.createWalkIn": "Create same-day entry", "checkin.walkInRequired": "Enter the required name fields before creating this entry.", "checkin.csvIntake": "CSV intake", "checkin.chooseCsv": "Choose CSV", "checkin.importSelected": "Import selected CSV", "checkin.editRegistration": "Edit registration", "checkin.phone": "Phone", "checkin.genre": "Genre", "checkin.region": "Region", "checkin.keepReview": "Keep marked for review", "checkin.linkPerson": "Match existing person", "checkin.moreActions": "More record actions", "checkin.canceledHelp": "This registration was canceled. Restore it before recording an arrival.", "checkin.allPresent": "Everyone on this entry is checked in.", "checkin.cashRecorded": "Cash recorded: {amount}", "checkin.teamProgress": "Team check-in: {present}/{total}", "checkin.nextSearch": "Ready for the next arrival — search to continue.", "checkin.noChange": "No change", "checkin.fee2v2": "¥5,200 per battler at the door", "checkin.feeU15": "¥3,200 at the door", "checkin.currentFee": "{amount} per arriving battler", "checkin.firstDrink": "first drink included",
  "checkin.noDivision": "No {division} registrations yet.", "checkin.noDivisionHelp": "Import a CSV or add a same-day registration to begin check-in.", "checkin.clearSearch": "Clear search and filters", "checkin.clearSearchHelp": "Try clearing the search or status filter.", "checkin.recordNextArrival": "Record next arrival · {amount}", "checkin.memberMissing": "Missing", "checkin.incomplete": "Incomplete", "checkin.teamArrival": "Team arrival: {present} of {total} checked in", "checkin.loading": "Loading Check-in…", "checkin.loadingHelp": "Loading the latest roster and arrival state.", "checkin.offlineTitle": "Check-in is offline", "checkin.offlineHelp": "You can keep searching the loaded roster. Arrivals and payments cannot be recorded until reconnection.", "checkin.blockedTitle": "Check-in blocked", "checkin.recordingArrival": "Recording arrival…", "checkin.undoing": "Undoing check-in…",
  "prelims.title": "Prelim control", "prelims.description": "Two judges score each checked-in entry from 1–10. The average determines seeded qualification.", "prelims.direct": "Direct bracket", "prelims.directHelp": "Prelims begin only above {cutoff} checked-in entries.", "prelims.runOrder": "Run order", "prelims.locked": "Order locked", "prelims.notGenerated": "Not generated", "prelims.lockOrder": "Lock entry order", "prelims.calculate": "Calculate rankings", "prelims.current": "Current", "prelims.onDeck": "On deck", "prelims.upNext": "Up next", "prelims.previous": "Previous", "prelims.next": "Next", "prelims.timer": "Shared timer", "prelims.start": "Start", "prelims.pause": "Pause", "prelims.reset": "Reset 45", "prelims.scores": "Judge scores", "prelims.judge1": "Judge 1", "prelims.judge2": "Judge 2", "prelims.saveScores": "Save scores", "prelims.qualification": "Qualification", "prelims.top": "Top {count}", "prelims.ranked": "{ranked}/{total} ranked", "prelims.rankHelp": "Lock the order, save every score, then calculate rankings.", "prelims.correction": "Ranking correction", "prelims.chooseEntry": "Choose entry", "prelims.newRank": "New rank", "prelims.reason": "Reason (required)", "prelims.saveCorrection": "Save correction", "prelims.cutoffTie": "Cut-off tie", "prelims.tieHelp": "Arrange tied entries from winner to loser, then save the right/left tie-break result.", "prelims.saveTie": "Save tie-break result", "prelims.noEntries": "No eligible entries yet.",
  "prelims.topQualify": "top {count} qualify", "prelims.generateOrder": "Generate the prelim order", "prelims.then": "Then: {name}", "prelims.endOrder": "End of order", "prelims.lateAppend": "Late fully checked-in arrivals append to the end.", "prelims.orderHelp": "Imported entry numbers stay in order; walk-ins follow.", "prelims.orderSaved": "Entry order locked.", "prelims.rankingsSaved": "Prelim rankings calculated.", "prelims.average": "Average", "prelims.invalidScore": "Invalid score: both judges must enter a whole number from 1 to 10.", "prelims.enterScoreRange": "Enter 1–10 only", "prelims.scoresSaved": "Scores saved for {name}.", "prelims.correctionHelp": "Choose an entry, rank, and reason for the correction.", "prelims.correctionSaved": "Ranking correction saved. Recalculate rankings to apply it.", "prelims.tieSaved": "Tie-break order saved.", "prelims.timerStart": "Shared timer started.", "prelims.timerPause": "Shared timer paused.", "prelims.timerReset": "Shared timer reset.", "prelims.loading": "Loading Prelims…", "prelims.loadingHelp": "Loading the current run order and score state.", "prelims.offlineTitle": "Prelims is offline", "prelims.offlineHelp": "The loaded order and scores are still visible. Scoring, timer controls, and rankings resume after reconnection.", "prelims.blockedTitle": "Lock the run order before scoring", "prelims.blockedHelp": "The checked-in entries need one locked entry order before any score can be recorded.", "prelims.openCheckIn": "Open Check-in", "prelims.directNext": "Use Bracket when you are ready to generate the direct bracket.", "prelims.scored": "Scored", "prelims.scoresMissing": "{count} scores missing", "prelims.missingScores": "{count} scores missing", "prelims.scoredEntry": "Scores saved", "prelims.saveAndNext": "Save scores & next", "prelims.savingAndNext": "Saving scores…", "prelims.retrying": "Retrying…", "prelims.allScoresSaved": "All prelim scores are saved", "prelims.scoreLedger": "Run order & saved scores", "prelims.scoreLedgerHelp": "Use this list to review or correct a specific entry without leaving the active score surface.", "prelims.standings": "Standings", "prelims.errorTitle": "Prelim update could not be saved", "prelims.errorHelp": "Review the latest entry state, then save again if it is still needed.", "prelims.moveUp": "Move earlier", "prelims.moveDown": "Move later",
  "bracket.title": "Tournament board", "bracket.description": "Complete each performance round, then select the winner indicated by the judges.", "bracket.generate": "Generate bracket", "bracket.replace": "Replace untouched bracket", "bracket.liveDisplay": "Floor display", "bracket.now": "NOW", "bracket.onDeck": "ON DECK", "bracket.noMatch": "No match selected", "bracket.timer": "Battle timer", "bracket.map": "Bracket map", "bracket.noBracket": "No bracket generated", "bracket.noBracketHelp": "Check in at least two entries, then generate the seeded bracket.", "bracket.matchControl": "Match control", "bracket.selectMatch": "Select a match", "bracket.left": "LEFT", "bracket.right": "RIGHT", "bracket.vs": "VS", "bracket.performance": "Performance", "bracket.completeRound": "Mark performance round complete", "bracket.record": "Record the winner", "bracket.tie": "Tie · run replay", "bracket.undo": "Undo decision", "bracket.complete": "Complete", "bracket.waiting": "Waiting", "bracket.recordResult": "Record result", "bracket.replay": "Replay active", "bracket.replayHelp": "Run one no-score replay round, then select the winner.",
  "bracket.replaceConfirm": "Replace the current untouched bracket?", "bracket.generated": "Seeded bracket generated.", "bracket.reloaded": "Bracket reloaded.", "bracket.roundComplete": "Performance round {round} marked complete.", "bracket.tieRecorded": "Tie recorded. Run the replay round.", "bracket.advances": "{name} advances.", "bracket.tieUndone": "Tie replay undone and the previous state restored.", "bracket.decisionUndone": "Match decision undone. Dependent matches were cleared.", "bracket.operatorResult": "Operator result", "bracket.seeds": "{count} seeded entries", "bracket.oneRound": "1 performance round", "bracket.finalRounds": "final {count} rounds", "bracket.matchNumber": "Match {number}", "bracket.recordedWinner": "Recorded winner", "bracket.replayCount": "Replay {count}", "bracket.winner": "Winner · {name}", "bracket.performanceProgress": "Performance {complete}/{total}", "bracket.openSeed": "Open seed", "bracket.waitingForPrevious": "Waiting for prior round", "bracket.roundProgress": "{complete}/{total} rounds complete", "bracket.finalHelp": "Final: complete both rounds before selecting the winner.", "bracket.performanceHelp": "Mark the performance complete, then record the operator result.", "bracket.selectOutcomeHelp": "Select the battler the judges pointed to, or select tie to run a replay.", "bracket.won": "{name} won",
  "reports.title": "Reports & records", "reports.description": "Review attendance, cash, staff activity, backups, and export the complete event record.", "reports.cashByType": "Cash by attendee type", "reports.entry": "Entry fees", "reports.2v2": "2v2 entry", "reports.u15": "U-15 entry", "reports.spectator": "Spectator entry", "reports.spectatorShort": "SPEC", "reports.drinks": "Drink money", "reports.drinksShort": "DRINK", "reports.total": "Total cash", "reports.exports": "Event exports", "reports.exportsHelp": "Exports use the currently selected interface language.", "reports.fullPackage": "Full event package", "reports.fullPackageHelp": "Download the whole event record in one file.", "reports.individualFiles": "Individual files", "reports.combinedCsv": "Combined CSV", "reports.combinedPdf": "Combined PDF", "reports.registrationCsv": "Registration CSV", "reports.prelimCsv": "Prelim CSV", "reports.bracketCsv": "Bracket CSV", "reports.staffCsv": "Staff CSV", "reports.exporting": "Preparing…", "reports.exportFailed": "Export could not be downloaded.", "reports.staffAttendance": "Staff attendance", "reports.audit": "Activity audit", "reports.time": "Time", "reports.staff": "Staff", "reports.action": "Action", "reports.target": "Target", "reports.noAudit": "No activity has been recorded.",
  "event.archiveConfirm": "Archive {name}? Operational changes will be locked until it is restored.", "event.deletePrompt": "Permanently delete {name}? This also removes its backups. Type DELETE to continue.", "event.restoreConfirm": "Restore this backup? Current registrations, payments, brackets, and timers will be replaced after a safety backup is created.",
  "toast.eventCreated": "Created {name}.", "toast.eventUpdated": "Event name updated.", "toast.eventArchived": "Event archived and removed from the active menu.", "toast.eventRestored": "Event restored.", "toast.eventDeleted": "Permanently deleted {name}.", "toast.staffPresent": "You are marked present on the staff log.", "toast.deleteCanceled": "Event was not deleted.", "toast.backupSaved": "Backup saved.", "toast.backupRestored": "Backup restored after creating a safety copy.", "toast.eventSettingsSaved": "Event settings saved.", "toast.walkInCreated": "Same-day entry created.", "toast.registrationUpdated": "Registration updated.", "toast.spectatorAdded": "Spectator payment recorded.", "toast.duplicateIgnored": "Duplicate warning ignored.", "toast.duplicateRemoved": "Duplicate registration removed.", "toast.checkInUndone": "Check-in undone.", "toast.checkedIn": "Check-in recorded.", "toast.personLinked": "Existing person record linked.", "toast.registrationRestored": "Registration restored.", "toast.registrationCanceled": "Registration canceled.",
  "reports.noData": "No report data is loaded.", "reports.noDataHelp": "Refresh the event connection to load the latest records.", "prelims.noEntriesHelp": "Check in eligible entries at Arrival Desk before setting a prelim order.", "state.saving": "Saving…", "overview.setup1": "Name the event.", "overview.setup2": "Set the event and prelim time.", "overview.setup3": "Then import or add entries at Arrival Desk.", "overview.safety": "Safety", "overview.manual": "Manual", "overview.eventSettings": "Event settings",
};

export const ja: Record<string, string> = {
  "checkin.controls": "受付操作",
  "app.staffOnly": "スタッフ専用", "app.openDesk": "イベント管理を開く", "app.authHelp": "共有アクセスコードを入力し、操作履歴に記録する名前と役割を入力してください。", "app.staffName": "スタッフ名", "app.roles": "役割", "app.accessCode": "スタッフアクセスコード", "app.enter": "スタッフ画面へ", "app.checking": "アクセス確認中…", "app.connecting": "The Menyu に接続中…", "app.connectingHelp": "スタッフアクセスとイベント接続を確認しています。", "app.connectionFailed": "The Menyu に接続できません。", "app.retry": "再試行", "app.sessionExpired": "スタッフセッションの期限が切れました。もう一度サインインしてください。", "app.chooseEventFirst": "この画面を開く前にイベントを選択してください。",
  "state.requestFailed": "操作を完了できませんでした。", "state.refreshed": "他のスタッフが更新しました。最新の状態を読み込みました。", "state.offlineTitle": "オフライン — 変更を停止中", "state.offlineHelp": "閲覧・検索は続けられます。再接続までライブ変更は記録できません。", "state.retryNow": "今すぐ再試行", "state.offlineWrite": "再接続してからライブ変更を記録してください。", "state.reconnected": "再接続しました。ライブ変更を記録できます。",
  "nav.now": "いま", "nav.checkin": "受付", "nav.prelims": "予選", "nav.bracket": "トーナメント", "nav.display": "表示", "nav.records": "記録", "nav.settings": "設定",
  "shell.control": "イベント管理", "shell.event": "開催中イベント", "shell.chooseEvent": "イベントを選択", "shell.currentPhase": "現在の進行", "shell.currentWorkspace": "現在の進行", "shell.openStatus": "表示中", "shell.workspaceNavigation": "作業画面メニュー", "shell.openNavigation": "メニューを開く", "shell.status": "イベント状況", "shell.nextMilestone": "次の予定", "shell.present": "受付済み", "shell.attention": "要対応", "shell.lastSync": "最終同期", "shell.syncedNow": "同期済み", "shell.syncing": "同期中…", "shell.offline": "オフライン・再接続中", "shell.notSynced": "未同期", "shell.prelimsUnset": "予選開始時刻 未設定", "shell.prelimsStarted": "予選開始済み", "shell.prelimsIn": "予選まで {time}", "shell.signedIn": "サインイン中", "shell.signOut": "サインアウト", "shell.rolesHelp": "役割に合わせて作業画面を案内します。すべての画面を編集できます。", "shell.customRole": "カスタム役割", "shell.connection": "接続設定", "shell.apiUrl": "バックエンドAPI URL", "shell.live": "LIVE",
  "shell.workspaceAttention": "要対応",
  "division.2v2": "2v2 バトル", "division.under15": "U-15 1v1", "status.Registered": "待機中", "status.Partial": "一部受付済み", "status.Checked in": "受付済み", "status.Canceled": "キャンセル", "status.paid": "支払済み", "status.paymentPending": "支払待ち",
  "common.open": "開く", "common.close": "閉じる", "common.edit": "編集", "common.save": "変更を保存", "common.cancel": "キャンセル", "common.restore": "復元", "common.delete": "削除", "common.rename": "名前変更", "common.archive": "アーカイブ", "common.reload": "再読み込み", "common.optional": "任意", "common.all": "すべて", "common.none": "なし", "common.yes": "はい", "common.no": "いいえ", "common.shown": "{count}件表示", "common.notSet": "未設定", "common.export": "出力", "common.back": "戻る",
  "attention.title": "確認待ち", "attention.partial": "未完了チーム", "attention.partialHelp": "未受付のメンバーがいるチーム", "attention.duplicates": "重複警告", "attention.duplicatesHelp": "重複の可能性を確認・無視・削除", "attention.review": "確認が必要な登録", "attention.reviewHelp": "インポート情報が不足または不明確", "attention.payment": "当日登録の支払待ち", "attention.paymentHelp": "当日作成後、受付が完了していません", "attention.late": "遅れて到着", "attention.lateHelp": "予選順確定後に追加されました", "attention.unscored": "予選スコア未入力", "attention.unscoredHelp": "受付済みエントリーに2名分の採点が必要", "attention.noOrder": "予選順が未確定", "attention.noBracket": "トーナメント未作成", "attention.openMatches": "未決着の試合", "attention.openMatchesHelp": "進行中の試合を完了してからトーナメントを終了してください", "attention.clear": "この画面に確認待ちはありません。",
  "activity.title": "最近の操作", "activity.viewAll": "すべて見る", "activity.empty": "操作履歴はまだありません。", "activity.system": "システム", "activity.check_in": "受付完了", "activity.undo_check_in": "受付を取り消しました", "activity.create_same_day_registration": "当日登録を作成", "activity.import_csv": "CSVをインポート", "activity.edit_registration": "登録情報を更新", "activity.add_spectator": "観戦者の支払を記録", "activity.enter_score": "予選スコアを入力", "activity.generate_prelim_order": "予選順を確定", "activity.create_bracket": "トーナメントを作成", "activity.record_bracket_decision": "試合結果を記録", "activity.control_shared_timer": "タイマーを更新", "activity.append_late_arrival": "遅刻到着を最後尾に追加", "activity.cancel_registration": "登録をキャンセル", "activity.restore_registration": "登録を復元", "activity.ignore_duplicate_warning": "重複警告を無視", "activity.remove_duplicate_registration": "重複登録を削除", "activity.create_event": "イベントを作成", "activity.update_event": "イベントを更新", "activity.archive_event": "イベントをアーカイブ", "activity.restore_event": "イベントを復元",
  "overview.title": "いま", "overview.pulse": "イベント状況", "overview.location": "会場", "overview.time": "開催時刻", "overview.teams": "2v2チーム", "overview.battlers": "受付済み出場者", "overview.spectators": "観戦者", "overview.cash": "現金合計", "overview.launchCheckin": "受付を開く", "overview.launchPrelims": "予選を開く", "overview.launchBracket": "トーナメントを開く", "overview.staffHome": "イベントデスク", "overview.startHere": "シフトを始める", "overview.startHereHelp": "次の現場作業に合うワークスペースを開いてください。", "overview.eventSummary": "イベント概要", "overview.checkinSummary": "{total}チーム中 {checkedIn}チームが受付済み", "overview.prelimsSummary": "{count}人が受付済み", "overview.bracketSummary": "トーナメント作成と結果の記録", "overview.workspaces": "イベントワークスペース", "overview.workspacesHelp": "いま必要な作業に合うワークスペースを選んでください。", "overview.attentionHelp": "受付で確認が必要な項目が {count}件あります。", "overview.reviewCheckin": "受付を確認", "overview.newEvent": "新規イベント", "overview.startDesk": "イベント管理を開始", "overview.createHelp": "新しいイベント記録を作成します。東京・日本標準時が初期設定です。", "overview.eventName": "イベント名", "overview.prelimsTime": "予選開始時刻", "overview.judge1": "ジャッジ1", "overview.judge2": "ジャッジ2", "overview.create": "イベントを作成", "overview.creating": "作成中…", "overview.manage": "イベント記録を管理", "overview.manageHelp": "終了したイベントはアーカイブすると一覧から非表示になります。完全削除するとバックアップも削除されます。", "overview.noEvents": "イベント記録はありません。", "overview.registrations": "登録 {count}件", "overview.staff": "会場スタッフ", "overview.markPresent": "出席を記録", "overview.noStaff": "スタッフ出席記録はありません。", "overview.backups": "イベントバックアップ", "overview.backupHelp": "大きな操作の前に復元ポイントを作成します。", "overview.reason": "理由（任意）", "overview.createBackup": "バックアップ作成", "overview.noBackups": "復元ポイントはありません。", "overview.restoreBackup": "バックアップを復元",
  "checkin.title": "受付 LIVE", "checkin.flowHelp": "登録を検索し、メンバーを確認してから一人ずつ受付します。", "checkin.search": "名前・チーム・ID・メール・Instagramで検索", "checkin.add": "登録を追加", "checkin.import": "CSV取込", "checkin.spectator": "観戦者を追加・¥2,700", "checkin.waiting": "待機中", "checkin.partial": "一部受付", "checkin.present": "受付済み", "checkin.review": "要確認", "checkin.registration": "登録", "checkin.division": "部門", "checkin.status": "状況", "checkin.payment": "支払", "checkin.noMatches": "一致する登録はありません。", "checkin.select": "登録を選択", "checkin.selectHelp": "一覧からチームまたは出場者を選び、受付を管理します。", "checkin.teamMembers": "チームメンバー", "checkin.member": "メンバー", "checkin.checkIn": "受付する", "checkin.undo": "受付を取り消す", "checkin.checkedAt": "{time} 受付済み", "checkin.collect": "{amount}を受領", "checkin.recordArrivalPayment": "受付と支払を記録", "checkin.entry": "エントリー", "checkin.drink": "ドリンク", "checkin.notes": "メモ", "checkin.noNotes": "メモはありません。", "checkin.early": "事前登録", "checkin.sameDay": "当日登録", "checkin.needsReview": "要確認", "checkin.duplicate": "重複の可能性", "checkin.ignoreDuplicate": "警告を無視", "checkin.removeDuplicate": "重複を削除", "checkin.addWalkIn": "当日登録を追加", "checkin.teamName": "チーム名", "checkin.battlerName": "出場者名", "checkin.memberNames": "メンバー名", "checkin.email": "連絡先メール", "checkin.instagram": "Instagram", "checkin.dob": "生年月日", "checkin.parent": "保護者", "checkin.createWalkIn": "当日登録を作成", "checkin.walkInRequired": "作成前に必須の名前欄を入力してください。", "checkin.csvIntake": "CSV取込", "checkin.chooseCsv": "CSVを選択", "checkin.importSelected": "選択したCSVを取込", "checkin.editRegistration": "登録情報を編集", "checkin.phone": "電話番号", "checkin.genre": "ジャンル", "checkin.region": "地域", "checkin.keepReview": "要確認のままにする", "checkin.linkPerson": "既存の人物と紐付け", "checkin.moreActions": "その他の登録操作", "checkin.canceledHelp": "この登録はキャンセルされています。受付を記録する前に復元してください。", "checkin.allPresent": "このエントリーの全員が受付済みです。", "checkin.cashRecorded": "受領済み: {amount}", "checkin.teamProgress": "チーム受付: {present}/{total}", "checkin.nextSearch": "次の到着者を検索できます。", "checkin.noChange": "変更なし", "checkin.fee2v2": "当日 ¥5,200／1人", "checkin.feeU15": "当日 ¥3,200", "checkin.currentFee": "到着した出場者1名につき {amount}", "checkin.firstDrink": "1ドリンク込み",
  "prelims.title": "予選コントロール", "prelims.description": "2名のジャッジが受付済みエントリーを1〜10点で採点し、平均点でシード順位を決定します。", "prelims.direct": "予選なし", "prelims.directHelp": "受付済みが{cutoff}組を超えた場合のみ予選を行います。", "prelims.runOrder": "出場順", "prelims.locked": "順番確定済み", "prelims.notGenerated": "未作成", "prelims.lockOrder": "エントリー順を確定", "prelims.calculate": "ランキング計算", "prelims.current": "現在", "prelims.onDeck": "次の出場", "prelims.upNext": "このあと", "prelims.previous": "前へ", "prelims.next": "次へ", "prelims.timer": "共有タイマー", "prelims.start": "開始", "prelims.pause": "一時停止", "prelims.reset": "45秒に戻す", "prelims.scores": "ジャッジ採点", "prelims.judge1": "ジャッジ1", "prelims.judge2": "ジャッジ2", "prelims.saveScores": "スコア保存", "prelims.qualification": "通過順位", "prelims.top": "上位{count}", "prelims.ranked": "{ranked}/{total} 順位確定", "prelims.rankHelp": "順番を確定し、全員の採点を保存してからランキングを計算します。", "prelims.correction": "順位修正", "prelims.chooseEntry": "エントリーを選択", "prelims.newRank": "新しい順位", "prelims.reason": "理由（必須）", "prelims.saveCorrection": "修正を保存", "prelims.cutoffTie": "通過ライン同点", "prelims.tieHelp": "同点者を勝者から順に並べ、左右判定の結果を保存します。", "prelims.saveTie": "同点決戦結果を保存", "prelims.noEntries": "対象エントリーはありません。",
  "prelims.topQualify": "上位{count}組通過", "prelims.generateOrder": "予選順を作成してください", "prelims.then": "その次：{name}", "prelims.endOrder": "出場順の最後", "prelims.lateAppend": "遅れて受付完了した出場者は最後尾に追加されます。", "prelims.orderHelp": "エントリー番号順を維持し、当日エントリーは最後尾に追加します。", "prelims.orderSaved": "エントリー順で予選順を確定しました。", "prelims.rankingsSaved": "予選ランキングを計算しました。", "prelims.average": "平均", "prelims.invalidScore": "無効な点数です。2名のジャッジとも1〜10の整数を入力してください。", "prelims.enterScoreRange": "1〜10のみ", "prelims.scoresSaved": "{name}の点数を保存しました。", "prelims.correctionHelp": "エントリー、順位、修正理由を入力してください。", "prelims.correctionSaved": "順位修正を保存しました。再計算すると反映されます。", "prelims.tieSaved": "同点決戦の順番を保存しました。", "prelims.timerStart": "共有タイマーを開始しました。", "prelims.timerPause": "共有タイマーを一時停止しました。", "prelims.timerReset": "共有タイマーをリセットしました。", "prelims.loading": "予選を読み込み中…", "prelims.loadingHelp": "現在の出場順と採点状況を読み込んでいます。", "prelims.offlineTitle": "予選はオフラインです", "prelims.offlineHelp": "読み込み済みの出場順と点数は確認できます。再接続まで採点、タイマー、順位計算はできません。", "prelims.blockedTitle": "採点前に出場順を確定してください", "prelims.blockedHelp": "受付済みエントリーをエントリー番号順で確定してから採点します。", "prelims.openCheckIn": "受付を開く", "prelims.directNext": "トーナメントを作る準備ができたら、サイドバーからトーナメントを開いてください。", "prelims.scored": "採点済み", "prelims.scoresMissing": "未入力スコア {count}件", "prelims.missingScores": "未入力 {count}件", "prelims.scoredEntry": "保存済み", "prelims.saveAndNext": "採点を保存して次へ", "prelims.savingAndNext": "採点を保存中…", "prelims.retrying": "再接続中…", "prelims.allScoresSaved": "全エントリーの採点を保存しました", "prelims.scoreLedger": "出場順・保存済みスコア", "prelims.scoreLedgerHelp": "進行中の採点を離れずに、特定エントリーの確認・修正ができます。", "prelims.standings": "順位表", "prelims.errorTitle": "予選の更新を保存できませんでした", "prelims.errorHelp": "最新の状態を確認して、必要ならもう一度保存してください。", "prelims.moveUp": "前へ移動", "prelims.moveDown": "後へ移動",
  "bracket.title": "トーナメントボード", "bracket.description": "各パフォーマンス終了後、ジャッジが示した勝者を選択します。", "bracket.generate": "トーナメント作成", "bracket.replace": "未使用トーナメントを再作成", "bracket.liveDisplay": "フロア表示", "bracket.now": "NOW", "bracket.onDeck": "ON DECK", "bracket.noMatch": "試合未選択", "bracket.timer": "バトルタイマー", "bracket.map": "トーナメント表", "bracket.noBracket": "トーナメント未作成", "bracket.noBracketHelp": "2組以上を受付後、シードトーナメントを作成してください。", "bracket.matchControl": "試合コントロール", "bracket.selectMatch": "試合を選択", "bracket.left": "左", "bracket.right": "右", "bracket.vs": "VS", "bracket.performance": "パフォーマンス", "bracket.completeRound": "パフォーマンス終了を記録", "bracket.record": "勝者を記録", "bracket.tie": "同点・再戦", "bracket.undo": "判定を取り消す", "bracket.complete": "完了", "bracket.waiting": "待機中", "bracket.recordResult": "結果を記録", "bracket.replay": "再戦中", "bracket.replayHelp": "採点なしの再戦を1ラウンド行い、勝者を選択してください。",
  "bracket.replaceConfirm": "現在の未使用トーナメントを作り直しますか？", "bracket.generated": "シードトーナメントを作成しました。", "bracket.reloaded": "トーナメントを再読み込みしました。", "bracket.roundComplete": "パフォーマンス{round}ラウンド目の完了を記録しました。", "bracket.tieRecorded": "同点を記録しました。再戦を行ってください。", "bracket.advances": "{name}が次へ進みます。", "bracket.tieUndone": "再戦を取り消し、前の状態に戻しました。", "bracket.decisionUndone": "試合結果を取り消し、後続試合をクリアしました。", "bracket.operatorResult": "運営判定入力", "bracket.seeds": "シード {count}組", "bracket.oneRound": "1パフォーマンスラウンド", "bracket.finalRounds": "決勝 {count}ラウンド", "bracket.matchNumber": "試合 {number}", "bracket.recordedWinner": "記録済み勝者", "bracket.replayCount": "再戦 {count}", "bracket.winner": "勝者・{name}", "bracket.performanceProgress": "パフォーマンス {complete}/{total}", "bracket.openSeed": "シード待ち", "bracket.waitingForPrevious": "前の試合を待機中", "bracket.roundProgress": "{complete}/{total}ラウンド完了", "bracket.finalHelp": "決勝：2ラウンド完了後に勝者を選択します。", "bracket.performanceHelp": "パフォーマンス完了を記録してから勝者を入力します。", "bracket.selectOutcomeHelp": "ジャッジが示した勝者を選ぶか、同点を選んで再戦を行います。", "bracket.won": "{name}の勝ち",
  "reports.title": "レポート・記録", "reports.description": "来場者、現金、スタッフ操作、バックアップを確認し、イベント全記録を出力します。", "reports.cashByType": "参加者区分別の現金", "reports.entry": "エントリー料金", "reports.2v2": "2v2エントリー", "reports.u15": "U-15エントリー", "reports.spectator": "観戦エントリー", "reports.spectatorShort": "観戦", "reports.drinks": "ドリンク代", "reports.drinksShort": "DRINK", "reports.total": "現金合計", "reports.exports": "イベント出力", "reports.exportsHelp": "現在選択中の言語で出力します。", "reports.fullPackage": "イベント一式", "reports.fullPackageHelp": "イベントの全記録を1つのファイルで出力します。", "reports.individualFiles": "個別ファイル", "reports.combinedCsv": "全データ CSV", "reports.combinedPdf": "全レポート PDF", "reports.registrationCsv": "登録 CSV", "reports.prelimCsv": "予選 CSV", "reports.bracketCsv": "トーナメント CSV", "reports.staffCsv": "スタッフ CSV", "reports.exporting": "準備中…", "reports.exportFailed": "出力をダウンロードできませんでした。", "reports.staffAttendance": "スタッフ出席", "reports.audit": "操作履歴", "reports.time": "時刻", "reports.staff": "スタッフ", "reports.action": "操作", "reports.target": "対象", "reports.noAudit": "操作履歴はありません。",
  "event.archiveConfirm": "{name}をアーカイブしますか？復元するまでイベント操作はロックされます。", "event.deletePrompt": "{name}を完全に削除しますか？バックアップも削除されます。続行するには DELETE と入力してください。", "event.restoreConfirm": "このバックアップを復元しますか？安全バックアップ作成後、現在の登録・支払・トーナメント・タイマーが置き換わります。",
  "toast.eventCreated": "{name}を作成しました。", "toast.eventUpdated": "イベント名を更新しました。", "toast.eventArchived": "イベントをアーカイブし、開催中一覧から非表示にしました。", "toast.eventRestored": "イベントを復元しました。", "toast.eventDeleted": "{name}を完全に削除しました。", "toast.staffPresent": "スタッフ出席記録に追加しました。", "toast.deleteCanceled": "イベントは削除されませんでした。", "toast.backupSaved": "バックアップを保存しました。", "toast.backupRestored": "安全コピーを作成してからバックアップを復元しました。", "toast.eventSettingsSaved": "イベント設定を保存しました。", "toast.walkInCreated": "当日登録を作成しました。", "toast.registrationUpdated": "登録情報を更新しました。", "toast.spectatorAdded": "観戦者の支払を記録しました。", "toast.duplicateIgnored": "重複警告を無視しました。", "toast.duplicateRemoved": "重複登録を削除しました。", "toast.checkInUndone": "受付を取り消しました。", "toast.checkedIn": "受付を記録しました。", "toast.personLinked": "既存の人物記録と紐付けました。", "toast.registrationRestored": "登録を復元しました。", "toast.registrationCanceled": "登録をキャンセルしました。",
  "checkin.noDivision": "{division}の登録はまだありません。", "checkin.noDivisionHelp": "CSVを取り込むか、当日登録を追加して受付を始めてください。", "checkin.clearSearch": "検索・フィルターをクリア", "checkin.clearSearchHelp": "検索語または状況フィルターをクリアしてください。", "checkin.recordNextArrival": "次の到着を記録・{amount}", "checkin.memberMissing": "未受付", "checkin.incomplete": "未完了", "checkin.teamArrival": "チーム受付：{total}人中{present}人が受付済み", "checkin.loading": "受付を読み込み中…", "checkin.loadingHelp": "最新の登録・受付状況を読み込んでいます。", "checkin.offlineTitle": "受付はオフラインです", "checkin.offlineHelp": "読み込み済みの登録は検索できます。再接続まで受付と支払は記録できません。", "checkin.blockedTitle": "受付を記録できません", "checkin.recordingArrival": "到着を記録中…", "checkin.undoing": "受付を取り消し中…", "reports.noData": "レポートデータがありません。", "reports.noDataHelp": "イベント接続を再読み込みして、最新の記録を読み込んでください。", "prelims.noEntriesHelp": "予選順を作る前に、受付で対象エントリーを受付してください。", "state.saving": "保存中…", "overview.setup1": "イベント名を決めます。", "overview.setup2": "開催時刻と予選時刻を設定します。", "overview.setup3": "次に受付でCSV取込または当日登録を追加します。", "overview.safety": "安全用", "overview.manual": "手動", "overview.eventSettings": "イベント設定",
};

// Keep staff-facing screen names short. The operational detail stays in the
// supporting copy where it is needed rather than competing with each heading.
Object.assign(en, {
  "activity.undo_spectator": "spectator addition undone",
  "activity.advance_prelim": "prelim performance changed",
  "shell.currentPhase": "Now",
  "shell.currentWorkspace": "Now",
  "overview.manage": "Past events",
  "overview.manageHelp": "Archive finished events. Delete only records you no longer need.",
  "overview.backups": "Backups",
  "overview.backupHelp": "Save a recovery point before a major operation.",
  "prelims.title": "Prelims",
  "reports.staffAttendance": "Crew",
  "reports.audit": "Activity",
});

Object.assign(ja, {
  "activity.undo_spectator": "観客の追加を取り消しました",
  "activity.advance_prelim": "予選の出番を変更しました",
  "shell.currentPhase": "いま",
  "shell.currentWorkspace": "いま",
  "overview.manage": "過去のイベント",
  "overview.manageHelp": "終了したイベントはアーカイブできます。不要になった記録だけ削除してください。",
  "overview.backups": "バックアップ",
  "overview.backupHelp": "大きな操作の前に復元ポイントを保存します。",
  "prelims.title": "予選",
  "reports.staffAttendance": "スタッフ",
  "reports.audit": "操作",
});

const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void; t: (key: string, params?: Params) => string }>({ language: "en", setLanguage: () => undefined, t: (key) => key });

Object.assign(en, {
  "checkin.undoSpectator": "Undo last spectator",
  "checkin.undoSpectatorConfirm": "Undo the latest spectator addition? This removes one spectator and reverses their recorded entry and drink payment. It does not issue a refund.",
  "toast.spectatorUndone": "Spectator addition undone; count and payment totals corrected.",
  "checkin.importReview": "Review import",
  "checkin.importApply": "Apply import",
  "checkin.importPreview": "Import preview",
  "checkin.importNoChanges": "Nothing has been saved yet.",
  "checkin.importMapping": "Mapped fields",
  "checkin.importWarnings": "Warnings",
  "checkin.importErrors": "Fix these rows before importing",
  "checkin.importSkipped": "blank rows skipped",
  "checkin.importHistory": "Import history",
  "checkin.latestImport": "Latest import",
  "checkin.undoImport": "Undo last import",
  "checkin.undoImportConfirm": "Undo the latest import? This removes only the registrations created by that import.",
  "checkin.importUndone": "Last import undone.",
  "checkin.importSaved": "Import saved.",
  "checkin.importRefreshFailed": "Import saved, but the latest roster could not be reloaded. Retry refresh before continuing.",
  "checkin.importSourceCsv": "CSV",
  "checkin.importSourcePdf": "PDF",
  "checkin.importEmpty": "No import history yet.",
  "state.savedRefreshFailed": "Saved, but the latest event state could not be reloaded. Retry before continuing.",
  "overview.rehearsal": "Rehearsal event",
  "overview.rehearsalHelp": "Separate test record. It does not mix with a live event.",
  "overview.live": "Live event",
  "overview.importSnapshot": "Import snapshot",
});
Object.assign(ja, {
  "checkin.undoSpectator": "直前の観客追加を取り消す",
  "checkin.undoSpectatorConfirm": "直前の観客追加を取り消しますか？観客数を1人減らし、記録された入場料とドリンク代を取り消します。返金は行われません。",
  "toast.spectatorUndone": "観客の追加を取り消し、人数と金額を修正しました。",
  "checkin.importReview": "取込を確認",
  "checkin.importApply": "取込を保存",
  "checkin.importPreview": "取込プレビュー",
  "checkin.importNoChanges": "まだ保存されていません。",
  "checkin.importMapping": "項目の対応",
  "checkin.importWarnings": "警告",
  "checkin.importErrors": "取込前に修正してください",
  "checkin.importSkipped": "空行をスキップ",
  "checkin.importHistory": "取込履歴",
  "checkin.latestImport": "最新の取込",
  "checkin.undoImport": "直前の取込を取り消す",
  "checkin.undoImportConfirm": "直前の取込を取り消しますか？その取込で作成された登録だけを削除します。",
  "checkin.importUndone": "直前の取込を取り消しました。",
  "checkin.importSaved": "取込を保存しました。",
  "checkin.importRefreshFailed": "取込は保存されましたが、最新の一覧を再読み込みできませんでした。続ける前に再試行してください。",
  "checkin.importSourceCsv": "CSV",
  "checkin.importSourcePdf": "PDF",
  "checkin.importEmpty": "取込履歴はありません。",
  "state.savedRefreshFailed": "保存しましたが、最新のイベント状態を再読み込みできませんでした。続ける前に再試行してください。",
  "overview.rehearsal": "リハーサルイベント",
  "overview.rehearsalHelp": "本番と分離されたテスト記録です。ライブイベントとは混ざりません。",
  "overview.live": "ライブイベント",
  "overview.importSnapshot": "取込スナップショット",
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => { try { return localStorage.getItem("menyuLanguage") === "ja" ? "ja" : "en"; } catch { return "en"; } });
  const setLanguage = (next: Language) => { setLanguageState(next); try { localStorage.setItem("menyuLanguage", next); } catch { /* Device storage may be unavailable. */ } };
  const value = useMemo(() => ({ language, setLanguage, t: (key: string, params: Params = {}) => {
    const template = (language === "ja" ? ja[key] : en[key]) ?? en[key] ?? key;
    return Object.entries(params).reduce((text, [name, replacement]) => text.replaceAll(`{${name}}`, String(replacement)), template);
  } }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useI18n = () => useContext(LanguageContext);
